version: "3.7"
services:
  bind:
    build: ./docker/bind
    volumes:
      - "./opt:/opt"
    environment:
      HOSTS: "asknicely.site; another-site.site; another.one"
      IPADDRESS: $IPADDRESS
    ports:
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"
    command: /opt/run.sh